/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.Telas;

import br.senai.sc.DAO.PatosDAO;
import br.senai.sc.DAO.UsuariopatosDAO;
import br.senai.sc.DAO.UsuariosDAO;
import br.senai.sc.Entidades.InfoUsuario;
import br.senai.sc.Entidades.Patos;
import br.senai.sc.Entidades.Usuariopatos;
import br.senai.sc.Entidades.Usuarios;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author bruni
 */
public class TelaJogo extends javax.swing.JFrame {
    Usuarios usu = new Usuarios();
    UsuariosDAO usuDAO = new UsuariosDAO();
    Patos pato = new Patos();
    PatosDAO patoDAO = new PatosDAO();
    Usuariopatos usupato = new Usuariopatos();
    UsuariopatosDAO usupatoDAO = new UsuariopatosDAO();
    InfoUsuario IU = new InfoUsuario();
    
    List<JLabel> ListaParedes = new ArrayList<>();
    List<JLabel> ListaMoedas = new ArrayList<>();
    Timer loop;
    int yi = 0;
    int xm = 0;
    int y = 400;
    int x = 275;
    int tempo = 0;
    int nd = 0;
    int velocidade = 2;
    int percurso = 0;
    int contador = 0;
    int contagem = 200;
    int distancia = 100;
    int aumenta = 0;
    int coletadas = 0;
    int j= 0 ;
    int poder = 0;
    int contadorpoder = 0;
    int cria = 50;
    int criadouro = 50;
    /**
     * Creates new form TelaJogo
     */
    public TelaJogo() {
        initComponents();
        setLocationRelativeTo(null);
        IniciarPerso();
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
//        y = Perso.getLocation().y;
//        x = Perso.getLocation().x;
        
        loop = new Timer(10 , new ActionListener() {
                
            @Override
            public void actionPerformed(ActionEvent ae) {
                
                
                PegarMoeda(ListaMoedas);
                MoverMoedas(ListaMoedas);
                MoverPersonagem(ListaParedes);
                RemoverParede(ListaParedes);
                MoverParede(ListaParedes);
                TempoDeCriação(ListaParedes);
                morrer();
                Outrosmetodos();
                
                Perso.setLocation(Perso.getLocation().x, y);
                jPanel1.add(Perso);
            }
           
        });
        requestFocus();
        loop.start();
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        Perso = new javax.swing.JLabel();
        morre = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pod = new javax.swing.JLabel();
        bar = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        Perso.setBackground(new java.awt.Color(0, 0, 0));
        Perso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Perso.setText("Perso");

        morre.setBackground(new java.awt.Color(255, 0, 0));
        morre.setEnabled(false);

        jLabel1.setText("Met");

        jLabel2.setText("0");

        jLabel3.setText("jLabel1");

        jLabel4.setText("jLabel1");

        jLabel5.setText("jLabel1");

        pod.setText("Uso do poder em: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(morre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(Perso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pod, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 424, Short.MAX_VALUE)
                        .addComponent(Perso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(225, 225, 225))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(morre, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 850));

        jMenu2.setText("Voltar");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        bar.add(jMenu2);

        setJMenuBar(bar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        
        for (JLabel parede : ListaParedes) {
                if ((parede.getLocation().getY()+30-velocidade>Perso.getLocation().getY() 
                        && parede.getLocation().getY()<Perso.getLocation().getY()+100) && 
                        ((Perso.getLocation().getX()==75 && parede.getLocation().getX()==230) ||
                        (Perso.getLocation().getX()==475 && parede.getLocation().getX()==230) || 
                        (Perso.getLocation().getX()==275 && parede.getLocation().getX()==20 && 
                        (evt.getKeyCode()==65 || evt.getKeyCode()==37)) || 
                        (Perso.getLocation().getX()==275 && parede.getLocation().getX()==440) 
                        && (evt.getKeyCode()==68 || evt.getKeyCode()==39)) ) {
                    nd = 1;
                }
        }
        
        if(nd==0){
            if((evt.getKeyCode()==68 || evt.getKeyCode()==39) && Perso.getLocation().getX()==275){
                Perso.setLocation(475, y);             
            }else if((evt.getKeyCode()==68 || evt.getKeyCode()==39) && Perso.getLocation().getX()==75){
                Perso.setLocation(275, y);
            }else if((evt.getKeyCode()==65 || evt.getKeyCode()==37) && Perso.getLocation().getX()==475){
                Perso.setLocation(275, y);
            }else if((evt.getKeyCode()==65 || evt.getKeyCode()==37) && Perso.getLocation().getX()==275){
                Perso.setLocation(75, y);
            }
        }
        
        nd=0;
        
    }//GEN-LAST:event_formKeyPressed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        loop.stop();
        int dialogButton = JOptionPane.OK_CANCEL_OPTION;
//        JOptionPane.showConfirmDialog(null, "Você perdera seu Progesso, Deseja continuar?");
        dialogButton = JOptionPane.showConfirmDialog( null, "Você perdera seu Progesso, Deseja continuar?", "Continuar", JOptionPane.OK_CANCEL_OPTION);
        if(dialogButton == JOptionPane.OK_OPTION){
            TelaMenuPrincipal abrir = new TelaMenuPrincipal();
            abrir.setVisible(true);
            dispose();
        }else if(dialogButton == JOptionPane.CANCEL_OPTION){
            loop.start();
        }
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogo().setVisible(true);
            }
        });
    }
    
    public void morrer(){
        if(Perso.getLocation().getY()>morre.getLocation().getY()){
            AlterarBD();
            JOptionPane.showMessageDialog(null, "Você Morreu");
            TelaPontuacao abrir = new TelaPontuacao(percurso, coletadas);
            abrir.setVisible(true);
            dispose();
            loop.stop();
//            y=100;
        }
    }
    
    public void AlterarBD(){
        int pontos;
        pontos = percurso+(coletadas*10);
        try {
            usu = usuDAO.getUsuarioPorID(IU.getIdusu());
        } catch (Exception ex) {
            Logger.getLogger(TelaJogo.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(usu.getPontos()<pontos){
            usu.setPontos(pontos);
        }
        usu.setMoedas(usu.getMoedas()+coletadas);
        try {
            usuDAO.alterar(usu);
        } catch (Exception ex) {
            Logger.getLogger(TelaJogo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void CriarParede(){
        JLabel parede = new JLabel();
        parede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arquivos/label.png")));
        parede.setRequestFocusEnabled(false);
        parede.setBounds(yi, -100, 190, 30);
        ListaParedes.add(parede);
        for (JLabel paredeAtual : ListaParedes) {
            jPanel1.add(paredeAtual);
        }
        parede.setVisible(true);
    }
    
    public void MoverParede(List<JLabel> paredes) {
        for (JLabel parede : paredes) {
            parede.setLocation((int) parede.getLocation().getX(), (int) parede.getLocation().getY()+velocidade);
        }
    }
    public void MoverMoedas(List<JLabel> moedas) {
        for (JLabel moeda : moedas) {
            moeda.setLocation((int) moeda.getLocation().getX(), (int) moeda.getLocation().getY()+velocidade);
        }
    }
    
    public void RemoverParede(List<JLabel> paredes){
        for (JLabel parede : paredes) {
            if (parede.getLocation().getY()>863) {
                ListaParedes.remove(parede);
                jPanel1.remove(parede);
                break;
            }
        }
    }
    
    public void MoverPersonagem(List<JLabel> paredes){
        for (JLabel parede : paredes) {
            if (parede.getLocation().getY()+30>=Perso.getY() && parede.getLocation().getY()+30<Perso.getLocation().getY()+100) {
                if(parede.getLocation().getX()<Perso.getX() && parede.getLocation().getX()+190>Perso.getX()){
                    if(PatoPool(parede)==true){
                        break;
                    }
                    y=y+velocidade;
                    setpoder();
                }
            }
        }
        
    }
    
    public void TempoDeCriação(List<JLabel> paredes){

        
        if(paredes.size()<=0){
            EscolhaParede();
            
        }else if(paredes.get(paredes.size()-1).getLocation().getY()>=distancia && cria>=criadouro){
        System.out.println(paredes.get(paredes.size()-1).getY());
            EscolhaParede();
            cria=0;
        }
    }
    
    public void EscolhaParede(){
        Random gerador = new Random();
        int escolhe = gerador.nextInt(7);
        int moeda = gerador.nextInt(100);
//        escolhe=4;
        switch(escolhe){
            case 0:
                yi = 1100;
                break;
            case 1:
                yi = 20;
                break;
            case 2:
                yi = 230;
                break;
            case 3:
                yi = 440;
                break;
            case 4:
                yi = 20;
                CriarParede();
                yi = 230;
                break;
            case 5:
                yi = 20;
                CriarParede();
                yi = 440;
                break;
            case 6:
                yi = 230;
                CriarParede();
                yi = 440;
                break;
                
        }
//        if(moedas.size()<=0){
//            EscolheMoedas(escolhe, moeda);
//        }if(moedas.get(moedas.size()-1).getLocation().getY()>=distancia){
////        System.out.println(moedas.get(moedas.size()-1).getY());
//            EscolheMoedas(escolhe, moeda);
//        }
        CriarParede();
        EscolheMoedas(escolhe, moeda);
        
    }
    
    public void CriarMoedas(){
        JLabel moeda = new JLabel();
        moeda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arquivos/moeda.gif" )));
        moeda.setRequestFocusEnabled(false);
        moeda.setBounds(xm, -100, 30, 30);
        ListaMoedas.add(moeda);
        for (JLabel MoedaAtual : ListaMoedas) {
            jPanel1.add(MoedaAtual);
        }
        moeda.setVisible(true);
       // JOptionPane.showMessageDialog(null, xm);
    }
    
    public void EscolheMoedas(int ini, int moeda){
        if(moeda>=0){
            Random gerador = new Random();
            int escolhe = gerador.nextInt(2);
//            JOptionPane.showMessageDialog(null, escolhe);
            switch(ini){
                case 0:
                    escolhe = gerador.nextInt(3);
                    if(escolhe==0){
                        xm=110;
                    }
                    if(escolhe==1){
                        xm=310;
                    }
                    if(escolhe==2){
                        xm=510;
                    }
                    break;
                case 1:
                    if(escolhe==0){
                        xm = 310;
                    }else{
                        xm = 510;
                    }
                break;
                
                case 2:
                    if(escolhe==0){
                        xm = 110;
                    }else{
                        xm = 510;
                    }
                break;
                    
                case 3:
                    if(escolhe==0){
                        xm = 110;
                    }else{
                        xm = 310;
                    }
                break; 
                    
                case 4:
                    xm = 510;
                break; 
                    
                case 5:
                    xm = 310;
                break; 
                    
                case 6:
                    xm = 110;
                break; 
                     
            }
            CriarMoedas();
        }
        
    }
    public void PegarMoeda(List<JLabel> moedas){
        for (JLabel moeda : moedas) {
            if(moeda.getLocation().getX()>Perso.getLocation().getX() && moeda.getLocation().getX()<Perso.getLocation().getX()+100 &&
               moeda.getLocation().getY()+30>Perso.getLocation().getY() && moeda.getLocation().getY()<Perso.getLocation().getY()+100){
                if(pato.getNome().equals("RockStarPato") || pato.getNome().equals("Patudao")){
                    coletadas++;
                }
                coletadas++;
                ListaMoedas.remove(moeda);
                jPanel1.getComponentAt(moeda.getLocation()).setVisible(false);
                 
                jPanel1.remove(moeda);
                
                jLabel2.setText(""+coletadas);
               break;     
            }else if(moeda.getLocation().getY()>900){
               ListaMoedas.remove(moeda);
               jPanel1.remove(moeda);
               break; 
            }
        }
//        System.out.println(moedas.size());
    }
    
    public void Poder(){
        switch(pato.getNome()){
            case "MedPato":
                MedPato();
                break;
                case "Patudao":
                MedPato();
                break;    
                
        }
    }
    
    public void MedPato(){
        if(poder==0){
            if(Perso.getLocation().getY()>400){
                y--;
            }
        }
    }
    
    public Boolean PatoPool(JLabel parede){
        if(pato.getNome().equals("PatoPool") || pato.getNome().equals("Patudao")){
            if(poder==0){
                ListaParedes.remove(parede);
                jPanel1.remove(parede);
                poder=30;
                if(pato.getNome().equals("Patudao")){
                    poder=15;
                }
                return true;
            }
        }
        return false;
    }
    
    public void IniciarPerso(){
        usu.setIdusuario(IU.getIdusu());
        usupato.setUsuarioID(usu);
        try {
            int cod = usupatoDAO.AcharPato(usupato);
            pato = patoDAO.getPatoPorID(cod);
        } catch (Exception ex) {
            Logger.getLogger(TelaJogo.class.getName()).log(Level.SEVERE, null, ex);
        }
        String foto = pato.getGif();
        Perso.setIcon(new javax.swing.ImageIcon(getClass().getResource(foto)));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arquivos/moeda.gif")));
        setpoder();
    }
    
    public void setpoder(){
        switch(pato.getNome()){
            case "MedPato":
                poder = 10;
                break;
            case "PatoPool":
                poder = 15;
                break;
            case "Patudao":
                poder = 15;
                break;
        }
        pod.setText("Uso do poder em: "+poder);
    }
    
    public void Outrosmetodos(){
        cria++;
        contador++;
        contadorpoder++;
        if(contadorpoder>=200){
            if(poder>0){
                contadorpoder=0;
                poder--;
//                        System.out.println(poder);
                pod.setText("Uso do poder em: "+poder);
            }
        }
        if(contador>=contagem){
            percurso++;
            contador=0;
            aumenta++;
        }
        if(aumenta==4){
            aumenta=0;
            if(velocidade<15){
                contagem=contagem-10;
                velocidade++;
                distancia = distancia+10;
                if(criadouro>5){
                    criadouro -=5;
                }
            }
        }
        jLabel3.setText(""+contagem);
        jLabel4.setText(""+velocidade);
        jLabel5.setText(""+aumenta);




        if(percurso==1){
            jLabel1.setText(percurso+" Metro");
        }else{
            jLabel1.setText(percurso+" Metros");
        }

        Poder();
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Perso;
    private javax.swing.JMenuBar bar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton morre;
    private javax.swing.JLabel pod;
    // End of variables declaration//GEN-END:variables
}
