/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.Telas;

import br.senai.sc.DAO.UsuariosDAO;
import br.senai.sc.Entidades.EmailValidator;
import br.senai.sc.Entidades.InfoUsuario;
import br.senai.sc.Entidades.Usuarios;
import br.senai.sc.Entidades.Usuarios_;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;

/**
 *
 * @author bruno_verbinnen
 */
public class TelaAtualizarInformacoes extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public TelaAtualizarInformacoes() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    Usuarios usu = new Usuarios();
    UsuariosDAO usuDAO = new UsuariosDAO();
    InfoUsuario IU = new InfoUsuario();
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nickname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        msglogin = new javax.swing.JLabel();
        msgnick = new javax.swing.JLabel();
        msgemail = new javax.swing.JLabel();
        msgsenha = new javax.swing.JLabel();
        msgconfirma = new javax.swing.JLabel();
        senha = new javax.swing.JPasswordField();
        confsenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Login:");

        login.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                loginCaretUpdate(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NickName:");

        nickname.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                nicknameCaretUpdate(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        jButton1.setText("Alterar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Email:");

        email.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                emailCaretUpdate(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Senha:");

        jLabel8.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Confirmar Senha:");

        msglogin.setFont(new java.awt.Font("Andalus", 0, 11)); // NOI18N
        msglogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msglogin.setText("O Login deve possuir pelo menos 5 caracteres ou já está em uso");

        msgnick.setFont(new java.awt.Font("Andalus", 0, 11)); // NOI18N
        msgnick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        msgemail.setFont(new java.awt.Font("Andalus", 0, 11)); // NOI18N
        msgemail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msgemail.setText("   ");

        msgsenha.setFont(new java.awt.Font("Andalus", 0, 11)); // NOI18N
        msgsenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msgsenha.setText("   ");

        msgconfirma.setFont(new java.awt.Font("Andalus", 0, 11)); // NOI18N
        msgconfirma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msgconfirma.setText("   ");

        senha.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                senhaCaretUpdate(evt);
            }
        });

        confsenha.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                confsenhaCaretUpdate(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arquivos/loja.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(msglogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nickname, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(msgnick, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(msgemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(email)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(msgsenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(senha)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(msgconfirma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(confsenha))))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(msglogin)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nickname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(msgnick)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(msgemail)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(senha))
                .addGap(6, 6, 6)
                .addComponent(msgsenha)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msgconfirma)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_loginCaretUpdate
        try {
            // TODO add your handling code here:
            usu.setLogin(login.getText());
            if(usuDAO.validarLoginregistrado(usu)==1){
                msglogin.setText("O Login já está em uso");
                msglogin.setVisible(true);
            }else{
                msglogin.setVisible(false);
                if(login.getText().length()<5){
                    msglogin.setText("O Login deve possuir pelo menos 5 caracteres");
                    msglogin.setVisible(true);
                }else{
                    msglogin.setVisible(false);
                }                
            }
        } catch (Exception ex) {
            Logger.getLogger(TelaAtualizarInformacoes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loginCaretUpdate

    private void nicknameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_nicknameCaretUpdate
        try {
            // TODO add your handling code here:
            usu.setNickname(nickname.getText());
            if(usuDAO.validarNickregistrado(usu)==1){
                msgnick.setText("O NickName já está em uso");
                msgnick.setVisible(true);
            }else{
                msgnick.setVisible(false);
                if(nickname.getText().length()<3){
                    msgnick.setText("O NickName deve possuir pelo menos 3 caracteres");
                    msgnick.setVisible(true);
                }else{
                    msgnick.setVisible(false);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(TelaAtualizarInformacoes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nicknameCaretUpdate

    private void emailCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_emailCaretUpdate
        try {
            // TODO add your handling code here:
            
            EmailValidator v = new EmailValidator();
            
            if(v.validate(email.getText())==true){
                usu.setEmail(email.getText());
                if(usuDAO.validarEmailregistrado(usu)==1){
                   msgemail.setText("E-mail já está em uso");
                   msgemail.setVisible(true);
                }else{
                   msgemail.setText(" ");
                   msgemail.setVisible(false);
                }
            }else{
                msgemail.setText("E-mail Inválido");
                msgemail.setVisible(true);
            }
            
        } catch (Exception ex) {
            Logger.getLogger(TelaAtualizarInformacoes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_emailCaretUpdate

    private void senhaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_senhaCaretUpdate
        // TODO add your handling code here:
        String senha1 = new String(senha.getPassword());
        if(senha1.length()<8){
            msgsenha.setText("A Senha deve possuir no minímo 8 caracteres");
            msgsenha.setVisible(true);
        }else{
            msgsenha.setVisible(false);
            if(senha1.length()>16){
                msgsenha.setText("A Senha deve possuir no máximo 16 caracteres");
                msgsenha.setVisible(true);
            }else{
                msgsenha.setVisible(false);
            }
        }
        
    }//GEN-LAST:event_senhaCaretUpdate

    private void confsenhaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_confsenhaCaretUpdate
        // TODO add your handling code here:
        String senha1 = new String(senha.getPassword());
        String senha2 = new String(confsenha.getPassword());
        
        if(!senha1.equals(senha2)){
            msgconfirma.setText("AS Senhas não correspondem");
            msgconfirma.setVisible(true);
        }else{
            msgconfirma.setVisible(false);
        }
    }//GEN-LAST:event_confsenhaCaretUpdate

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        JPasswordField password = new JPasswordField(10);
        password.setEchoChar('*'); 
        // Cria um rótulo para o campo
        JLabel rotulo = new JLabel("Digite a Senha Atual para Confirmação:\n");
        // Coloca o rótulo e a caixa de entrada numa JPanel:
        JPanel entUsuario = new JPanel();
        entUsuario.add(rotulo);
        entUsuario.add(password);
        // Mostra o rótulo e a caixa de entrada de password para o usuario fornecer a senha:
        JOptionPane.showMessageDialog(null, entUsuario, "Acesso restrito", JOptionPane.PLAIN_MESSAGE);
        
//        JOptionPane pane = new JOptionPane(entUsuario);
//        JDialog dlgPane = pane.createDialog(null, "Confirmação");
//        pane.setBackground(Color.WHITE);
//        dlgPane.setBackground(Color.WHITE);
//        dlgPane.setVisible(true);
        // O programa só prossegue quando o usuário clicar o botao de OK do showMessageDialog. 
        // Aí, é só pegar a senha:
        // Captura a senha:
        String atual = password.getText();
        
        try {
            usu = usuDAO.getUsuarioPorID(IU.getIdusu());
        } catch (Exception ex) {
            Logger.getLogger(TelaAtualizarInformacoes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(atual.equals(usu.getSenha())){
            if(login.getText().length()>0 && msglogin.isVisible()==false && msgnick.isVisible()==false
                    && msgemail.isVisible()==false && msgsenha.isVisible()==false 
                    && msgconfirma.isVisible()==false){

                String senha1 = new String(senha.getPassword());
                try {
                    usu.setLogin(login.getText());
                    usu.setNickname(nickname.getText());
                    usu.setEmail(email.getText());
                    usu.setSenha(senha1);
                    usu.setAdm(false);
                    usu.setMoedas(usu.getMoedas());
                    usu.setPontos(usu.getPontos());
                    usuDAO.alterar(usu);
                    JOptionPane.showMessageDialog(null, "Alterar com Sucesso!");
                    TelaInformacoesdeUsuario Abrir = new TelaInformacoesdeUsuario();
                    Abrir.setVisible(true);
                    dispose();
                } catch (Exception ex) {
                    Logger.getLogger(TelaAtualizarInformacoes.class.getName()).log(Level.SEVERE, null, ex);
                }

            }else{
                JOptionPane.showMessageDialog(null, "Há informações não preenchidas ou preenchidas incorretamente");
            }
        }else{
            JOptionPane.showMessageDialog(null, "As senhas São Diferentes");
            TelaInformacoesdeUsuario Abrir = new TelaInformacoesdeUsuario();
            Abrir.setVisible(true);
            dispose();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TelaInformacoesdeUsuario abrir = new TelaInformacoesdeUsuario();
        abrir.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        msglogin.setVisible(false);
        msgnick.setVisible(false);
        msgemail.setVisible(false);
        msgsenha.setVisible(false);
        msgconfirma.setVisible(false);
        try {
            usu = usuDAO.getUsuarioPorID(IU.getIdusu());
        } catch (Exception ex) {
            Logger.getLogger(TelaAtualizarInformacoes.class.getName()).log(Level.SEVERE, null, ex);
        }
        login.setText(usu.getLogin());
        nickname.setText(usu.getNickname());
        email.setText(usu.getEmail());
        senha.setText(usu.getSenha());
        confsenha.setText(usu.getSenha());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarInformacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarInformacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarInformacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarInformacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtualizarInformacoes().setVisible(true);
            }
        });
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confsenha;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField login;
    private javax.swing.JLabel msgconfirma;
    private javax.swing.JLabel msgemail;
    private javax.swing.JLabel msglogin;
    private javax.swing.JLabel msgnick;
    private javax.swing.JLabel msgsenha;
    private javax.swing.JTextField nickname;
    private javax.swing.JPasswordField senha;
    // End of variables declaration//GEN-END:variables
}
